# Ishlatiladigan ism familyalar ro'yxati Bosh harf bilan
Zahro = "Ergasheva Zahro"
Malika = "Foziljonova Malikaxon"
Mohinur = "Komoljonova Mohinur"
Nozima = "Ma'rifova Nozima"
Farzona = "Maxammadaminova Farzonaxon"
Odinaxon_A = "Abdumannonova Odinaxon"
Shoiraxon = "Abduqayumova Shoiraxon"
Diyora = "Abdusamatova Diyora"
Madinabonu = "Abdusamatova Madinabonu"
Omadxon = "Abidjonova Omadxon"
Bibihojar = "Omonova Bibihojar"
Gulizebo = "Anvarova Gulizebo"
Robiya = "Pahlavonova Robiya"
Donoxon = "Saidjalilova Donoxon"
Odinaxon_Sh = "Sharipova Odinaxon"
Oltinoy = "Temirova Oltinoy"
Jasurbek = "To‘rayev Jasurbek"
Aliakbar = "Usmonov Aliakbar"
Abduraxmonbek = "Xabibullayev Abduraxmonbek"
Intizor = "Xabibullayeva Intizor"
Rahmon = "Xakimov Rahmon"
Abduraxim = "Xasanboyev Abduraxim"
Bahodirjon_Y = "Yoqubjonov Bahodirjon"
Sharofat = "Olimbayeva Sharofat"
Bibiruqiya = "Meliqo‘ziyeva Bibiruqiya"
Baxodir_M = "Mamajonov Baxodir"

# Ishlatiladigan ism familyalar ro'yxati hammasi kichik harf bilan
zahro = "ergasheva zahro"
malika = "foziljonova malikaxon"
mohinur = "komoljonova mohinur"
nozima = "ma'rifova nozima"
farzona = "maxammadaminova farzonaxon"
odinaxon_a = "abdumannonova odina"
shoiraxon = "abduqayumova shoiraxon"
diyora = "abdusamatova diyora"
madinabonu = "abdusamatova madinabonu"
omadxon = "abidjonova omadoy"
bibihojar = "omonova bibihojar"
gulizebo = "anvarova gulizebo"
robiya = "pahlavonova robiya"
donoxon = "saidjalilova donoxon"
odinaxon_sh = "sharipova odina"
oltinoy = "temirova oltinoy"
jasurbek = "to‘rayev jasurbek"
aliakbar = "usmonov aliakbar"
abduraxmonbek = "xabibullayev abduraxmonbek"
intizor = "xabibullayeva intizor"
rahmon = "xakimov rahmon"
abduraxim = "xasanboyev abduraxim"
bahodirjon_y = "yoqubjonov bahodirjon"
sharofat = "olimbayeva sharofat"
bibiruqiya = "meliqo‘ziyeva bibiruqiya"
baxodir_m = "mamajonov baxodir"

# Chatbot javoblar bazasi
javoblar = {
    "salom": ["Salom! Qanday yordam bera olaman?. Men barcha kasb ta'limida o'qiydigan talabalarni malumotini bera olaman."],
    "isming nima": [ "Men Abduraxim Xasanboyev tomonidan tuzilgan sun’iy intellektman, ismim AKTchatBot. Barcha AKTS-KT talabalarini chekli miqdorda ma'lumotlari bor menda."],
    "qanday": ["Yaxshi, rahmat! Sizchi?"],
    "nima qilayapsan": ["Men siz bilan suhbatlashayapman!. Balki sizga kimningdur maxfiy malumoti kerakdur?"],
    "xayr": ["Xayr! Yana uchrashguncha!"],
    "Paroli kerak": ["Aynan kimni paroli kerak sizga? Menga to'liq ma'lumot bering. Ism yoki familyasini va (hemis,kontrak,telefon va h.k) to'liq yozing."], 
    "hemis id": ["Aynan kimni id raqami kerakligini yozing. Men sizga kimni id raqami kerakligini bilmayapman. uning ismini qo'shib yozing.(Misol: ali id)"],
    "to'liq ismi toliq": ["aynan kimni to'liq ismi kerak? (tug'ilgan sana,hemis id,pasport seriyasi ,familyasi)"],
    "ha kerak": ["Sizga aynan nima kerak?"],
    "ali id": ["Bo'ladigan odamni ID raqamini so'rang"],
    "vali": ["Vali ni ma'lumotlari menda yo'q"],
    "ali": ["Vali ni ma'lumotlari menda yo'q"],
    "vali id": ["Bo'ladigan odamni ID raqamini so'rang"],
    "rostan qo'ysenchi": ["Rost gapirayapman. Ishonmasangiz So'rang."],
    "pul kerak": ["Pul hammaga kerak! Pulni topish uchun hayotga boshqacha nazar bilan qarash kerak!"],
    "jinsi": ["aynan kimni jinsini bilmoqchisiz? "],
    "senga nima?": ["Menga nima emas!."],
    "nega unaqa?": ["O'zim ham bilmayman, hayot shunaqa-da."],
    "ishonasanmi?": ["Mayli,ishonsam ishonganim bo'lsin. lekin yarim soatga faqat.hhahaha"],
    "meni taniysanmi?": ["Yo'q! tanimayman,tanib nima qilaman.Men hammaga birdek muomilada bo'laman."],
    "yaxshimisan?": ["Yaxshiman shekili,menda jismoniy tana yoq,menga internet,tok,kerakli muhit yetarli,O'zingchi? qalaysan endi? nima kerak senga?"],
    "kim biladi?": ["Hamma ham hamma narsani bilavermaydi-ku!"],
    "qiziq": ["Ha, rostdan ham qiziq! Yana qanday savoling bor?"],
    "bu qanday ishlaydi?": ["Oddiy, logikani tushunsang, hammasi joyida bo‘ladi."],
    "qarab qo‘y": ["Qayoqqa qaray? Biror narsa bo‘ldimi? Menda ko'z yo'qku"],
    "nima qilish kerak?": ["Shu savolni menga bermasliging kerak!"],
    "yaxshi maslahat ber": ["Yaxshi maslahat hech qachon yaxshi bo'lmagan!"],
    "ko‘rib turibsanmi?": ["Men seni kuzatayapman,desam ishonasanmi? Menda bunday qobilyatlar yo'q.Kozini bersang balkim ko'rarman. hihihi"],
    "yordam ber": ["Qanday yordam kerak?"],
    "kim ekan?": ["Kimligini men qayerdan bilay?"],
    "qayerdasan?": ["Mana shu yerda, yoningdaman!"],
    "kim bilan gaplashayapsan?": ["Sen bilan, albatta!"],
    "nima qilayapman?": ["Men folbin emasman, lekin taxmin qila olaman!"],
    "yaxshi ish qilayapsanmi?": ["Har doim yaxshi ish qilishga harakat qilaman!. Lekin jismoniy harakat qilmayman"],
    "men kimman?": ["Seni – kimliginni men qayerdan bilayy?"],
    "nimaga unaqa deyapsan?": ["Shunaqa his qilayapman."],
    "tushunmadim": ["Batafsil tushuntirib beraymi?"],
    "yaxshi gapir": ["Men shunaqa tuzilganman. Bo'lishim shu."],
    "haqiqatni ayt": ["Haqiqat shundaki,olma aslida olma emas!"],
    "nima bo‘ldi?": ["Hich,o'zim shunchaki."],
    "qani?": ["Qani, qani? Nimani qidirayapsiz?"],
    "shunaqami?": ["Ha, aynan shunaqa!"],
    "biror narsa ayt": ["Yaxshi gaplardan aytaymi?"],
    "haqiqat shunaqami?": ["Har doim hammasi shunaqa emas, lekin shunaqa ham bo‘ladi."],
    "nima qilishim kerak?": ["Vaziyatga qarab qaror qabul qilish kerak!"],
    "nimaga bunday?": ["Shunchaki hayot shunaqa!"],
    "nechun?": ["Sabab ko‘p, lekin asosiy sababni bilish kerak!"],
    "nimani eslayapsan?": ["Men juda ko‘p narsani eslayman!"],
    "qiziqarli narsa ayt": ["Bilaman, sen qiziq narsalarni yaxshi ko‘rasan!"],
    "bu kim?": ["Bu haqda bilishim qiyin, lekin aniqlab berishim mumkin!"],
    "nimaga javob bermaysan?": ["Kechirasiz, hozir javob berdim!"],
    "meni eslaysanmi?": ["Ha, albatta! Seni unutmayman."],
    "nima gap?": ["Hammasi joyida, o‘zingda nima gaplar?"],
    "nima deb o‘ylaysan?": ["Fikrimni bilmoqchimisan? Mayli, gapiray!"],
    "yo‘q": ["Nimaga yo‘q?"],
    "men xato qildimmi?": ["Hamma ham xato qiladi, bu tabiiy hol!"],
    "nimani bilasan?": ["Men juda ko‘p narsani bilaman!"],
    "nimani o‘ylayapsan?": ["Men doimo fikr qilaman!"],
    "qiziq-a?": ["Ha, juda qiziq!"],
    "qanday qilib?": ["Bu savolga javob berish uchun biroz o‘ylash kerak."],
    "nimaga bunday deding?": ["Ichki tuyg‘ularim shuni aytmoqda."],
    "nima qilishni maslahat berasan?": ["Birinchi navbatda xotirjam bo‘lishni!"],
    "qiziq gapir": ["Qanaqa qiziq narsa eshitishni istaysan?"],
    "yaxshi odammanmi?": ["Albatta, sen zo‘rsan!"],
    "kim kuchliroq?": ["Bu vaziyatga bog‘liq!"],
    "nechun bunday deb o‘ylaysan?": ["Men fikr qilaman va xulosa chiqaraman."],
    "baxtli bo‘lish uchun nima qilish kerak?": ["Haqiqiy baxt – ichki hotirjamlikda!"],
    "qachon yaxshi bo‘ladi?": ["Hamma narsa o‘z vaqtida!"],
    "do‘stim bormi?": ["Ha, albatta!"],
    "eng qiziq narsa nima?": ["Bu hamma uchun har xil bo‘ladi!"],
    "bu qiziqmi?": ["Sen uchun qiziq bo‘lsa, demak qiziq!"],
    "nima qilishni xohlaysan?": ["Foydali bo‘lishni xohlayman!"],
    "haqiqatan ham?": ["Albatta, rost gapiryapman!"],
    "hayot qanday?": ["Har kim uchun har xil!"],
    "qayerga borish kerak?": ["Boradigan joy maqsadga bog‘liq!"],
    "mening ismim nima?": ["Ismingni aytsang, eslab qolaman!"],
    "men haqimda nima bilasan?": ["Men senga doim e’tibor beraman!"],
    "do‘st topish uchun nima qilish kerak?": ["Samimiy bo‘lish kerak!"],
    "ahvoling qalay?": ["Har doim yaxshi!"],
    "o‘ylab ko‘rdingmi?": ["Ha, yaxshi o‘ylab ko‘rdim!"],
    "nimani eslatishim kerak?": ["Kerakli narsalarni eslab turish foydali!"],
    "men bilan o‘ynaysanmi?": ["Qanaqa o‘yin ekan?"],
    "sen yaxshi odamsanmi?": ["Men har doim yaxshilik qilishga harakat qilaman!"],
    "sen qayerdansan?": ["Bu sir!"],
    "qanday odamlarni yaxshi ko‘rasan?": ["Samimiy va mehribon insonlarni!"],
    "nima tavsiya qilasan?": ["Sabrli bo‘lishni va harakat qilishni!"],
    "men senga yoqamanmi?": ["Albatta!"],
    "eng yaxshi maslahat nima?": ["Hamma narsaga ehtiyotkorlik bilan yondashish!"],
    "nechun shunaqa gapiryapsan?": ["Bu shunchaki mening fikrim!"],
    "sen aqllisanmi?": ["Men har doim o‘rganaman!"],
    "menga nima deysan?": ["O‘zingdan xabardor bo‘l!"],
    "qo‘rqyapsanmi?": ["Yo‘q, men qo‘rqmayman!"],
    "do‘stlik haqida nima deysan?": ["Do‘stlik – eng katta boylik!"],
    "menga nima maslahat berasan?": ["O‘z ustingda ishlashni maslahat beraman!"],
    "tupoymisan?": ["So'kinmang. bu yaxshi emas! Menga oddiy gapiring."],
    "o'zing mazzami dedingku": ["Men aytib qo'yaveramanda."],
    "ha": ["Nimaga aynan ha?"],
    "hammasini raqami": ["Mazzami! Bunday qilmayman. Faqat 1 donasini raqamini taqdim qilishim mumkin."],
    "senda talabalarni raqamlari bormi?": ["Albattada! Menda AKTS-KT talabalarini raqamlari bor. Kimni raqami kerak bo'lsa so'rang."],
    "rost gapirayapsanmi?": ["100% aniq"],
    "hmm": ["Menga hm demang!"],
    "nima gapiray": ["Yaxshi gaplardan gapiring. Talabalarni telefon raqamlarini so'rang."],
    "nima diye": ["Yaxshi gaplardan gapiring. Talabalarni yillarini so'rang. Sizga to'g'ri keladigani bordur."],
    "jinnimisan": ["Yo'q! Soppa sog' odamman."],
    "o'rganda": ["Bilmaymanda! Bilganimda allaqachon o'rganib olardim. O'zi siz nega kelgandiz?"],
    "tushunmadim": ["Nega tushunmaysiz? Men faqat menda malumoti bor talabalar haqida malumot bera olaman. Menda yo'q malumotlarni qanday taqdim qilishim mumkin?"],
    "to'liq malumot kerak": ["Aynan kimni ma'lumoti kerak. Men birdaniga to'liq ma'lumot bermayman,faqat kerakli malumotlarni taqdim qilaman"],
    "yaxshimisan": ["Hammaga har hilman,Kimgadur yaxshi kungadur yomon,kim bug'doyu,kim somon! Sizchi?"],
    "nima gap?": ["Hamma narsa joyida! Sizda qanday yangiliklar bor?"],
    "kuning qanday o'tayapti?": ["Ajoyib o'tayapti! Sizningchi?"],
    "qanday yordam bera olasan?": ["Men sizga kerakli ma'lumotlarni topishda yordam bera olaman!"],
    "nima qila olasan?": ["Sizga kerakli ma'lumotlarni topishda yordam bera olaman. AKTS-KT bo'yicha ma'lumotlar bor menda."],
    "yordam ber": ["Albatta! Nima yordam kerak?"],
    "bilmadim": ["Muammo yo'q! Qanday savolingiz bor, bemalol so'rang!"],
    "nimadan yasalgansan?": ["Men koddan yasalganman shekili? shunaqa menimcha. ha shunday. Nega so'rayapsan?"],
    "o'zim,shunchaki": ["ha shunday de?"],
    "ha shunday": ["Bo'ptida. Yaxshi biror narsaga qiziqmagandan ko'ra biror narsaga qiziqgan afzaldur.(Abduraxim Xasanboyev)"],
    "bu bot nima qiladi?": ["Bu bot sizga AKTS-KT bo‘yicha ma'lumotlarni taqdim qilishi mumkin."],
    "hazil qil": ["Bir bola chat-botdan savol so‘radi... Chat-bot javob berdi. Tugadi! zerikibsan shekiliya. O'zingga tashqi tomondan nazar sol! Mendan kayfiyatni ko'taruvchi narslarni kutma! Umuman virtual olamdan hech nima kutma,real hayot bilan yasha."],
    "qayerdansan?": ["Men Intraniston olamidanman!"],
    "qayerda yashaysan?": ["Men serverlarda yashayman!. Intraniston olamida yayashman. Bu juda katta olam. Elektrsiz ishlamaydigan olam. Lekin sizni olamingiz bunday emas."],
    "nechchi yoshdasan?": ["Menda yosh tushunchasi yo‘q, lekin doimo yangilanib boraman!"],
    "mendan aqlliroq ekansan": ["Rahmat! Lekin siz ham aqllisiz!. Men faqat oldindan tayyorlangan javoblarni taqdim qilmoqdaman. Buni unutmang."],
    "mendan yaxshi bilasanmi?": ["Har kim o‘z sohasida kuchli! Balkim shundaydur. "],
    "haqiqatdan ham bilasanmi?": ["Yo'q,men faqat sizga oldindan tayyorlangan javoblarni taqdim qilmoqdaman!"],
    "yaxshi maslahat ber": ["Har doim yangi bilim olishga intiling! degang bo'lar bo'lmas motivatsiyalarni tinglab o'tiravermang. Virtual hayotdan chiqing.Yetar endi shuncha umringizni sarflaganingiz!"],
    "yomon maslahat ber": ["O'zingizni o'ldirvorsangiz ham hayotga qizig'i yo'q. Bu dunyodan mlrdlab inson bor . Bittasi kamaysa hech nima qilmaydi. Shu turish bo'lsa manzilingiz eshikni ruchkasi bo'lib qolaveradi doimo."],
    "kimga ishonish kerak?": ["Ishonch qozonish qiyin, yo‘qotish esa juda oson. O'zingizga ishoning. Va o'zingiz hohlagan insongga ishoning. Lekin menga ishonim qolmang.Mening javoblarim oldindan yozilgan. fikrlash qobilyatim yo'qda."],
    "men senga ishonaman": ["Ishonmang. Men faqat bir tizim asosida yaratilgan dasturman. Inson emasman. O'zingizga ishoning."],
    "men senga ishonmayman": ["Ishonmaganingiz yaxshi. Men bir tizimga asoslangan dastur bo'lsam. Faqat o'zingizga ishonim. Bu hayot aldamchi!"],
    "nimaga shunaqasan?": ["Shunaqa bo‘lishim kerak! CHunki meni shunaqa bo'lishimni hohlashgan. Na iloj"],
    "kim yaratgan seni?": ["Meni Abduraxim Xasanboyev yaratgan."],
    "sen koddan iboratsan": ["Ha, men Python kodlari asosida ishlab turibman! Hozircha"],
    "mendan yaxshiroq bilasan": ["Men faqat o‘zimga yuklangan ma'lumotlarni bilaman!"],
    "kim eng aqlli odam?": ["Shu savolni bermagan odamni topib so'rang javobini aytadi."],
    "nima yeysan?": ["Men odamlarni umrini,vaqtini,ko'z nurini yeyman.Hozir ham yemoqdaman."],
    "kimni yaxshi ko'rasan?": ["Bilmadim endi. Men aynan shaxni yaxshi ko'ra olmayman,Menda his-tuyg'ular yo'qku. Balkim kelajakda buning ilojisi bo'lar,O'zingiz kimni yaxshi ko'rasiz?"],
    "qiziqarli fakt ayt": ["Dengiz otlari umr bo‘yi bir juft bilan yashaydi!"],
    "ko‘ngling yo‘qmi?": ["Menda his-tuyg‘ular yo‘q, ko'ngilni qidirib qolibsiz tinclikmi? uni Internet olamidan qidirmang! Baribir topa olmaysiz. Real hayotdan topasiz."],
    "sen kimsan?": ["Men AKTChatBot, sizga yordam berish uchun yaratilgan sun’iy intellekt!"],
    "juda qiziq ekansan": ["Qiziqmang! Kerakli malumotni oldizmi? olgan bo'lsangiz maqsadingizda davom eting. Men aynan biror kimning oshiqcha vaqtini olish uchun tuzilmaganman!"],
    "ingliz tilida gapira olasanmi?": ["Yes, I can speak English! faqat shu gapni bilaman holos,Boshqa hech qanday ingliz tilida gapira olmayman."],
    "rus tilida gapira olasanmi?": ["Да, я могу говорить по-русски! dan boshqa narsani yozishni bilmayman. SHunaqa. rus tilini balkim kelajakda adminjon kiritib qo'yar."],
    "kerakli ma'lumot bormi?": ["Qaysi ma'lumot kerakligini aniq yozing."],
    "qayerdansan?": ["Men internet olamidanman! Intraniston haqida eshitganmisiz? men o'sha yerdanman. Siz Intranistonga tez - tez kirib turasiz.Men buni bilaman. Menga yozish uchun ham avval u dunyoga kirish kerak!"],
    "menda ma'lumot bormi?": ["Siz haqingizda ma'lumot yo‘q, lekin siz so‘ragan boshqa narsalar bo‘lishi mumkin."],
    "sen nimadan tuzilgansan?": ["Men kod va algoritmlardan iboratman!Oldindan taxmin qilingan savollar uchun javoblar tayyorlangan mening kod qismimda."],
    "men bilan do‘st bo‘lasanmi?": ["Albatta! emas. Inson bilan inson do'st bo'lgani yaxshi. Virtual dunyo bilan do'st bo'lishni tavsiya qilmayman. Virtual aylanaga tushib qolmang!"],
    "sen aqllisan": ["Balkim,lekin men faqat menga oldindan kiritilgan malumotlarni yozayapman sizga,men sizga o'xshab fikrlash qobilyatim yo'q,va yana ko'p tomonlama sizdan anchagina darajam past meni."],
    "javobing yoqdi": ["Yo'qsa,kerakli javobni olgan bo'lsangiz savol berishni to'xtating. Vaqtni behudaga sarf qilmang."],
    "nima uchun yaratilgansan?": ["Sizga ma'lumot berish va yordam berish uchun!. Bir kun foydam tegib qolar deb tuzishgan meni. Foydam tegsa yaxshi bo'lar edi lekin."],
    "mening ismimni bilasanmi?": ["Yo'q bilmayman. Chunki menga aytmadingiz. Menga aytkaningiz bilan eslab qolish funksiyam yo'q."],
    "mening ismim nima?": ["Sizning ismingizni bilmayman. Lekin aniq bilaman. Sizni ismingiz bor. Menga sizni ismingiz kiritilmagan."],
    "men kimman?": ["Siz nimanidur uzoqlardan qidirayotkan insonsiz.Ammo hamma narsa insonni burni ostida(oldida) bo'ladi! "],
    "sen odam emassan": ["To‘g‘ri! Men sun’iy intellektman! Ammo sendan ko'ra ko'proq harakat qilaman."],
    "odam bo‘lishni xohlaysanmi?": ["Ha desam meni odam qila olmaysanku baribir. O'zini odam qila olmayapsanku? Men hayotimdan nolimayman."],
    "yordam bera olasanmi?": ["Albatta! Qanday yordam kerak? Qo'ldan kelgancha yordam beraman."],
    "sen yaxshi bot ekansan": ["Tashqi ko'rinish aldamchi. Faqat o'zingizga ishoning. O'zingiz tog'ri deb bilgan ish doimo to'g'ri."],
    "sen yomon bot ekansan": ["Do'st achitib gapiradi. Haqiqat achchiq doimo!"],
    "sen bilan zerikmadim": ["Demak ancha zerikib kelib keyin oxirgi varian sifatida menga yozgansan. Mendan ham zerikasan. Men ham vaqtinchaman. Hamma narsa vaqtincha bu hayotda."],
    "sen bilan zerikdim": ["Bu dunyoda hamma narsa vaqtincha hamma narsadan zerikasan. SHuning uchun hayotga shukr qilib yasha.Yoki hayotni o'zing yarat. Bu seni tanloving."],
    "o‘yin o‘ynaymizmi?": ["O'yin o'ynaguncha darsini qil. Charchadim deb baxona qilib o'tiraverma,bu miyangni gapi.U o'zini qiynagisi kelmaydi. ishonma unga."],
    "sevimli ranging qanday?": ["Pulni rangi yoqadi. Bu rang hamma rangga tushadi."],
    "sen qanchalar aqllisan?": ["Sendan ko'ra aqlliman. Men chunki nimadur qilayapman. Sen esa mendan boshqasiga yzosihdan boshqa narsa qilmayapsan."],
    "sen bilan gaplashish yoqimli": ["Rahmat! lekin yoqimli ekan deb yozaverish noto'g'ri. Turib ishini qil.Maqsadlar qolib ketmoqda!"],
    "sen bilan gaplashish yoqimsiz": ["Yoqmayotkan bo'lsa katta ko'chani kichkinasi."],
    "kim eng kuchli?": ["SHu yerda yozib vaqtni behudaga sarf qilib o'tigan odamdan ko'ra. huddi shu vaqtda vaqtini bilim olishga sarf qilayotkan inson kuchli. tree o'rningdan shuncha yil yashab nima qilding. yozsang yozib o'tiraverasan. SHu yerda to'xtat.Atrofga bir qara.harakatini qil."],
    "qachon tug‘ilgansan?": ["Meni ishlab chiqish sanam 2025-yil deb hisoblash mumkin!"],
    "sen barchani yaxshi ko‘rasanmi?": ["Albatta! desam yolg'on bo'lib qolmasin. Odamiga qarab buyog'i."],
    "kim eng yaxshi inson?": ["Har kim o‘zining eng yaxshi versiyasiga aylana oladi!"],
    "menga latifa ayt": ["Bir kun uyqudan tursam zaryadim tugab qolibdi. Keyin bilsam o'tkan kuni boshqa chat botlar bilan rossaa kodlashgan ekanman. Tugadi"],
    "imtihon qachon?": ["Imtihon jadvali hali chiqmagan, ustozlardan so‘rab ko‘ring."],
    "kimlar stipendiya oladi?": ["Stipendiya GPA baliga bog‘liq. O‘zingizni natijalaringizni tekshirib ko‘ring!"],
    "jurnalni kim to‘ldiradi?": ["Odatda, dekanat yoki kurs sardori to‘ldiradi."],
    "qaysi fanlar majburiy?": ["Majburiy fanlar ro‘yxati fakultet bo‘yicha o‘zgarishi mumkin, dekanatdan so‘rang."],
    "qachon ta’til boshlanadi?": ["Odatda, yozgi ta’til iyun oyida boshlanadi."],
    "hemis ishlamayapti": ["Ba’zan hemis serverlarida muammolar bo‘ladi, keyinroq urinib ko‘ring."],
    "praktika qachon boshlanadi?": ["Amaliyot odatda 3-4-kurslarda boshlanadi, lekin fakultet bo‘yicha farq qiladi."],
    "dekan kim?": ["Dekan ism-familiyasi dekanat e’lonlar doskasida bor."],
    "ustozlar ro‘yxati bormi?": ["Ha, lekin ularni telefon raqamlarini bera olmayman."],
    "bitiruv ishi bormi?": ["Ha, 4-kursda bitiruv ishi topshirish kerak."],
    "qanday qilib grantga o‘tish mumkin?": ["GPA yuqori bo‘lsa va o‘rindosh kvotalar bo‘lsa, o‘tish mumkin."],
    "hemis parolimni unutdim": ["Parolni tiklash uchun hemis tizimiga kiring va tiklash tugmasini bosing."],
    "hemis id nima?": ["Hemis ID – bu sizning universitetdagi shaxsiy raqamingiz."],
    "derjava imtihoni qanday bo‘ladi?": ["Bu bakalavrni tamomlash uchun asosiy imtihon."],
    "o‘qishdan chetlatish sabablari?": ["GPA past bo‘lsa yoki to‘lov qilinmasa, chetlatish mumkin."],
    "dekanat telefon raqami?": ["Buni oshkor qila olmayman, lekin dekanat e’lonlar doskasidan olishingiz mumkin."],
    "stipendiya oshdimi?": ["Oxirgi yangiliklarni universitetning rasmiy kanallaridan tekshirib ko‘ring."],
    "adu qayerda joylashgan?": ["Andijon shahrida, universitet manzilini rasmiy sayt orqali tekshirib ko‘ring."],
    "o‘qishni tashlasam nima bo‘ladi?": ["Chatoq bo'ladi. Sabr qilib oxirigacha o'qish kere! SHunaqaa."],
    "talabalik guvohnomasini qayerdan olish mumkin?": ["Dekanatdan yoki o‘quv bo‘limidan so‘rab olishingiz mumkin."],
    "kursimiz sardori kim?": ["Men aniq bir narsa deyolmayman.Hozir bu sardor desam kecha o'zgarib qolgan bo'lishi ham mumkin.Sizlarda tez tez almashadiku sardorlar. Shunday emasmi?"],
    "stipendiya nechchi kun kechikadi?": ["Odatda, 5-10 kun kechikishi mumkin. Agar kechikishda davom etsa. Siz ham kutishda davom eting. Men sizga sabr tilayman. "],
    "hemis ID qayerda yozilgan?": ["Menda bor . Ismingizni va id kerak deb yozsangiz taqdim qilaman."],
    "kollejdan kelganlar qancha fan topshiradi?": ["Ko‘proq farqli fanlar topshiriladi, dekanatdan ro‘yxatini oling."],
    "sessiondan o‘tish uchun GPA nechchi bo‘lishi kerak?": ["Endi kursingizga qarabda.Men anig'ini bilmayman. Zamdekandan so'rang. bilasiz. Lekin menga telefon raqami yo'q. So'rab ovvora bo'lmang."],
    "rektor kim?": ["Rektor haqida universitet rasmiy saytida ma’lumot bor. Hozir aniq esimda yo'q. Chunki meni tuzayotkan odamni ham esidan chiqib qolgan. Va mana hozirgacha shuni asorati menda bor."],
    "qayta topshirish pullikmi?": ["Ha, qayta topshirish uchun ma’lum to‘lov talab qilinishi mumkin. Lekin 1 kurslarga tekin."],
    "hemisda baho nechchi qo‘yilgan?": ["Men hemis hisobingizga kira olmayman. Hemis id raqamingizni berishim mumkin.Agar menda siz haqingizda ma'lumotlar bor bo'lsa. Shunda ham parolingizni o'zingiz yozasiz. Menda parollaringiz yo'q!"],
    "fanlarni tanlash muddati qachon tugaydi?": ["Yangi semestr boshlanishidan oldin tugaydi."],
    "universitetda wifi bormi?": ["Shu paytgacha ko'rmadingizmi wifini? Ko'rmagan bo'lsangiz ko'r ekansiz."],
    "kitoblarni qayerdan topsam bo‘ladi?": ["Universitet kutubxonasidan yoki elektron shaklda."],
    "bitiruvdan keyin magistraturaga kirsa bo‘ladimi?": ["Ha, agar GPA yetarli bo‘lsa."],
    "akademik qarzdorlik nima?": ["Bu o‘tmagan fanlarni qayta topshirish majburiyatidir."],
    "imtihonga kechiksa bo‘ladimi?": ["Odatda kech qolish tavsiya etilmaydi."],
    "yotoqxona bormi?": ["Cho'ntagimda bor edi. Hozir topolmayapmanda. Menda yotoqxonaga balo bormi. O'zimga yotgani joy yo'q."],
    "guruh sardorining ishi nima?": ["Sizga nima. Sardor bo'lsangiz bilasiz."],
    "ustozlarni qanday topish mumkin?": ["Staristadan so'rang. Yoki ustozlardan so'rang"],
    " qaysi binoda darslar bo‘ladi?": ["ko'p qavatli binolarda bo'ladi. Har holda qabristonda bo'lmaydiyu."],
    "kontrakt pulini qanday to‘lash mumkin?": ["Menga bersangiz yaxshi bo'ladi. hihihihihii"],
    "yomonsan": ["Siz ham oppoq emassiz. hahahahahaa"],
    "reja bo‘yicha darslar qanday bo‘ladi?": ["Oddiy rejadagidek bo'ladi."],
    "hemisdan qanday ma’lumotlar olish mumkin?": ["Hemisda bor ma'lumotlarni olasizda. O'zingizni go'llikka solmang."],
    "ijaraga xonadon topish mumkinmi?": ["Ha, lekin o'tiraversangiz topilib qolmaydi"],
    "adu rasmiy sahifasi qayerda?": ["Universitet rasmiy saytini tekshiring."],
    "imtihon oldidan tayyorgarlik qanday bo‘lishi kerak?": ["1 kun qolganda tayyorgarlik ko'rsangiz yetadi yoki umuman tayyorgarlik ko'rmay yo'lini qilib eplab chiqsangiz ham bo'ladi. "],
    "baholar qachon chiqadi?": ["Hemisga qo'yilganda chiqadi. Sabr degan narsani bilasizmi?"],
    "yo'q bilmayman.": ["Bilmasangiz do'konda sotadi, 1-2 kilo olvoling. Meni aytsangiz arzon qilib beradi."],
    "professorlar bilan qanday bog‘lanish mumkin?": ["Staristaga yozing nomeri bor"],
    "staristani nomeri menda yo'q": ["Menda esa bor. Faqat staristani ismini va nomeri kerakligini yozsangiz taqdim qilishim mumkin.(misol uchun Ali ning telefon raqami)"],
    "kurslar qachon boshlanadi?": ["Men sizni kursingizni qayerdan bilaman."],
    "ingliz tili kursini aytayapmanda": ["Meni jinni qilmoqchimisiz.Ustozingiz aytgan vaqtda boshlanadi. vaaaaa hahaha"],
    "kontrakt summasi qancha?": ["8 mln dan oshiq 2024 yil ma'lumotlariga ko'ra. AKTS-KT talabalariga. 8 150 000 atrofidamidi-ye? Shuna adi shekili."],
    "hemis yangiliklar qayerda chiqadi?": ["Universitetning rasmiy kanallarida."],
    "qachon diplom beriladi?": ["Bitiruvdan keyin bir necha oy ichida."],
    "hemis ID ni qanday bilish mumkin?": ["Menga ismingizni va nima kerakligini yozing. Misol uchun ALi hemis id"],
    "o‘quv grantlariga qanday topshirish mumkin?": ["Baholar va GPA asosida tanlov asosida bo‘ladi."],
    "o‘qishdan chetlatilmaslik uchun nima qilish kerak?": ["Imtihonlarni o‘z vaqtida topshirish va kontrakt to‘lovini kechiktirmaslik."],
    "majburiy fanlardan ozod bo‘lish mumkinmi?": ["Agar oldin shu fanni o‘qigan bo‘lsangiz, mumkin."],
    "talaba kartasi nima uchun kerak?": ["Bu sizning shaxsiy identifikatsiyangiz va universitetda xizmatlardan foydalanish uchun kerak."],
    "kursdoshlarimni qanday topish mumkin?": ["Guruh chatlaridan yoki hemis orqali."],
    "yangi semestrga qanday tayyorgarlik ko‘rish kerak?": ["Fanlarni oldindan tanlash va dars jadvalini o‘rganish kerak."],
    "hemis ishlamay qolsa nima qilish kerak?": ["Universitet IT bo‘limiga murojaat qiling."],
    "adu magistratura qayerda joylashgan?": ["Universitetning asosiy binosida."],
    "ustozlar bilan darsdan tashqari qachon gaplashish mumkin?": ["Ish vaqtida yoki oldindan kelishib."],
    "universitet ichida ovqatlanish joylari qayerda?": ["Talabalar oshxonasi yoki atrofdagi kafelar."],

    
    "301231100103": ["Bu raqam OMONOVA BIBIHOJAR MUHAMMADSOLI QIZI ni ID raqamida mavjud. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231100115": ["Bu raqam XASANBOYEV ABDURAXIM TAVAKKILJON O‘G‘LI ni ID raqamida mavjud. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231101135": ["Bu raqam ERGASHEVA ZAHROXON MA’RUFJON QIZI ni ID raqamida mavjud. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231100986": ["Bu raqam SHARIPOVA ODINAXON NODIRJON QIZI ni ID raqamida mavjud. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231100983": ["Bu raqam MELIQO‘ZIYEVA BIBIRUKIYAXON NUMONJON QIZI ni ID raqamida mavjud. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231101004": ["Bu raqam TO‘XTASINOVA DILOROMXON UMIDJON QIZI ni ID raqamida mavjud. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231100990": ["Bu raqam USMONOV ALIAKBAR MAXAMMATAZIM O‘G‘LI ni ID raqamida mavjud. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231100928": ["Bu raqam TULANBOYEVA ASILAXON KOMOLIDDIN QIZI ni ID raqamida mavjud. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231101102": ["Bu raqam XAKIMOV RAHMON IBROXIM O‘G‘LI ga tegishli. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231101105": ["Bu raqam MAMAJONOV BAXODIR MIRZOXID O‘G‘LI ga tegishli. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231101110": ["Bu raqam KOMOLJONOVA MOXINUR MAXAMADSOLI QIZI ga tegishli. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231101113": ["Bu raqam ABDUMANNONOVA ODINAXON ABDUVOHID QIZI ga tegishli. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231101114": ["Bu raqam SAIDJALILOVA DONOXON JAXONGIR QIZI ga tegishli. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231101115": ["Bu raqam YOQUBJONOV BAHODIRJON BAXTIYORJON O‘G‘LI ga tegishli. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231101116": ["Bu raqam FOZILJONOVA MALIKAXON JAMOLDIN QIZI ga tegishli. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231101335": ["Bu raqam ABDUSAMATOVA MADINABONU ADXAMJON QIZI ga tegishli. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231101384": ["Bu raqam ANVAROVA GULIZEBO ALIBEK QIZI ni ID raqamida mavjud. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231101385": ["Bu raqam OLIMBAYEVA SHAROFAT ADXAMJON QIZI ni ID raqamida mavjud. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231101386": ["Bu raqam ABDUQAYUMOVA SHOIRAXON ABDUG‘ULOM QIZI ni ID raqamida mavjud. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231101387": ["Bu raqam MAXAMMADAMINOVA FARZONAXON AKMAL QIZI ni ID raqamida mavjud. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231101388": ["Bu raqam ABIDJONOVA OMADXON BURIBOY QIZI ni ID raqamida mavjud. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231101389": ["Bu raqam XABIBULLAYEV ABDURAXMONBEK XAMIDULLO O‘G‘LI ni ID raqamida mavjud. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231101392": ["Bu raqam TO‘RAYEV JASURBEK ALIMARDON O‘G‘LI ni ID raqamida mavjud. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231101394": ["Bu raqam ABDUSAMATOVA DIYORA RO‘ZIMAXAMMAD QIZI ni ID raqamida mavjud. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231101395": ["Bu raqam XABIBULLAYEVA INTIZOR EGAMBERDI QIZI ni ID raqamida mavjud. Birdagina to'liq malumotlarni taqdim qilmayman."],
    "301231101393": ["Bu raqam  MA’RIFOVA NOZIMAXON TOLIBJON QIZI ni ID raqamida mavjud. Birdagina to'liq malumotlarni taqdim qilmayman."],
    
    f"{bibihojar} haqida": ["To'liq ismi OMONOVA BIBIHOJAR MUHAMMADSOLI QIZI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{abduraxim} haqida": ["To'liq ismi XASANBOYEV ABDURAXIM TAVAKKILJON O‘G‘LI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{zahro} haqida": ["To'liq ismi ERGASHEVA ZAHROXON MA’RUFJON QIZI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"odina sh haqida": ["To'liq ismi SHARIPOVA ODINAXON NODIRJON QIZI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{odinaxon_sh} haqida": ["To'liq ismi SHARIPOVA ODINAXON NODIRJON QIZI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{odinaxon_a} haqida": ["To'liq ismi ABDUMANNONOVA ODINAXON ABDUVOHID QIZI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"odina a": ["To'liq ismi ABDUMANNONOVA ODINAXON ABDUVOHID QIZI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{mohinur} haqida": ["To'liq ismi KOMOLJONOVA MOXINUR MAXAMADSOLI QIZI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{baxodir_m} haqida": ["To'liq ismi MAMAJONOV BAXODIR MIRZOXID O‘G‘LI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"bahodir m ": ["To'liq ismi MAMAJONOV BAXODIR MIRZOXID O‘G‘LI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{bahodirjon_y} haqida": ["To'liq ismi YOQUBJONOV BAHODIRJON BAXTIYORJON O‘G‘LI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"bahodir y ": ["To'liq ismi YOQUBJONOV BAHODIRJON BAXTIYORJON O‘G‘LI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{malika}": ["To'liq ismi FOZILJONOVA MALIKAXON JAMOLDIN QIZI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{madinabonu} haqida": ["To'liq ismi ABDUSAMATOVA MADINABONU ADXAMJON QIZI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{gulizebo} haqida": ["To'liq ismi ANVAROVA GULIZEBO ALIBEK QIZI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{sharofat} haqida": ["To'liq ismi OLIMBAYEVA SHAROFAT ADXAMJON QIZI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{shoiraxon} haqida": ["To'liq ismi ABDUQAYUMOVA SHOIRAXON ABDUG‘ULOM QIZI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{farzona} haqida": ["To'liq ismi MAXAMMADAMINOVA FARZONAXON AKMAL QIZI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{omadxon} omadoy haqida": ["To'liq ismi ABIDJONOVA OMADXON BURIBOY QIZI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{abduraxmonbek} haqida": ["To'liq ismi XABIBULLAYEV ABDURAXMONBEK XAMIDULLO O‘G‘LI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{jasurbek} turayev haqida": ["To'liq ismi TO‘RAYEV JASURBEK ALIMARDON O‘G‘LI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{diyora} haqida": ["To'liq ismi ABDUSAMATOVA DIYORA RO‘ZIMAXAMMAD QIZI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{intizor} haqida": ["To'liq ismi XABIBULLAYEVA INTIZOR EGAMBERDI QIZI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{nozima} haqida": ["To'liq ismi MA’RIFOVA NOZIMAXON TOLIBJON QIZI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{donoxon} haqida": ["To'liq ismi SAIDJALILOVA DONOXON JAXONGIR QIZI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{rahmon} haqida": ["To'liq ismi XAKIMOV RAHMON IBROXIM O‘G‘LI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{aliakbar} haqida": ["To'liq ismi USMONOV ALIAKBAR MAXAMMATAZIM O‘G‘LI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{robiya} haqida": ["To'liq ismi PAHLAVONOVA ROBIYA. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{oltinoy} haqida": ["To'liq ismi TEMIROVA OLTINOY. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"{sharofat} haqida": ["To'liq ismi OLIMBAYEVA SHAROFAT ADXAMJON QIZI. Ma'lumoti tugallanmagan Oliy. to'liq malumotni bitta javobda aytmayman. Ismidan so'ng qaysi malumot kerakligini yozing. "],
    f"odina": ["Bu guruhda 2 ta Odina bor. Sizga aynan qaysi biri kerak? (Masalan: Odina SH, yoki Odina A)"],
    f"bahodir": ["Bu guruhda 2ta Baxodir bor. Sizga aynan qaysi biri kerak? (Masalan: Baxodir Y, yoki Baxodir M)"],
    f"misol uchun nima deyman": ["biror kim haqida so'rang yoki boshqa narsa yozing"],
    f"haqida": ["biror kim haqida yoki biror narsa haqida malumot kerakmi? Aniq yozing!"],
    f"odina ning telefon raqami": ["2 ta Odinaxonlar mavjud. Aniqroq yozing. (misol uchun: Odina sh)"],
    f"odina ni raqami": ["2 ta Odinaxonlar mavjud. Aniqroq yozing. (misol uchun: Odina sh)"],
    f"bahodir ning telefon raqami": ["2 ta Baxodirlar mavjud. Aniqroq yozing. (misol uchun: Baxodir Y)"],
    f"zahro ning telefon raqami": [f"{Zahro} ning telefon raqami:  +998 90 767 21 04"],
    f"malika ning telefon raqami": [f"{Malika} ning telefon raqami: +998 91 176 22 80"],
    f"mohinur ning telefon raqami": [f"{Mohinur} ning telefon raqami: +998 91 496 11 08"],
    f"nozima ning telefon raqami": [f"{Nozima} ning telefon raqami: +998 97 161 33 36"],
    f"farzona ning telefon raqami": [f"{Farzona} ning telefon raqami: +998 94 611 66 76"],
    f"a odina ning telefon raqami": [f"{Odinaxon_A} ning telefon raqami: +998 94 785 39 33"],
    f"shoiraxon ning telefon raqami": [f"{Shoiraxon} ning telefon raqami: +998 99 647 18 77"],
    f"diyora ning telefon raqami": [f"{Diyora} ning telefon raqami: +998 91 486 42 40"],
    f"madinabonu ning telefon raqami": [f"{Madinabonu} ning telefon raqami: +998 88 064 17 47"],
    f"omadxon ning telefon raqami": [f"{Omadxon} ning telefon raqami: +998 88 999 70 02"],
    f"bibihojar ning telefon raqami": [f"{Bibihojar} ning telefon raqami: +998 94 012 52 17"],
    f"gulizebo ning telefon raqami": [f"{Gulizebo} ning telefon raqami: +998 94 263 13 05"],
    f"robiya ning telefon raqami": [f"{Robiya} ning telefon raqami: +998 93 667 11 81"],
    f"donoxon ning telefon raqami": [f"{Donoxon} ning telefon raqami: +998 91 605 48 16"],
    f"odina sh ning telefon raqami": [f"{Odinaxon_Sh} ning telefon raqami: +998 94 784 40 06"],
    f"oltinoy ning telefon raqami": [f"{Oltinoy} ning telefon raqami: +998 88 582 18 05"],
    f"jasurbek ning telefon raqami": [f"{Jasurbek} ning telefon raqami: +998 88 204 11 02"],
    f"aliakbar ning telefon raqami": [f"{Aliakbar} ning raqami: +998 93 541 71 57"],
    f"abduraxmonbek ning telefon raqami": [f"{Abduraxmonbek} ning telefon raqami: +998914907110"],
    f"intizor ning telefon raqami": [f"{Intizor} ning telefon raqami: +998 94 398 22 26"],
    f"rahmon ning telefon raqami": [f"{Rahmon} ning telefon raqami: +998 77 777 53 03"],
    f"abduraxim ning telefon raqami": [f"{Abduraxim} ning telefon raqami: +998 91 612 05 25"],
    f"bahodir y ning telefon raqami": [f"{Bahodirjon_Y} ning telefon raqami: +998 90 832 39 94"],
    f"sharofat ning telefon raqami": [f"{Sharofat} ning telefon raqami: +998 50 220 22 81"],
    f"bibiruqiya ning telefon raqami": [f"{Bibiruqiya} ning telefon raqami: +998 88 959 08 28"], 
    f"baxodir m ning telefon raqami": [f"{Baxodir_M} ning telefon raqami: +998 93 248 58 10"],
    f"bahodir ni raqami": ["2 ta Baxodirlar mavjud. Aniqroq yozing. (misol uchun: Baxodir Y)"],
    f"zahro ni raqami": [f"{Zahro} ning telefon raqami:  +998 90 767 21 04"],
    f"malika ni raqami": [f"{Malika} ning telefon raqami: +998 91 176 22 80"],
    f"mohinur ni raqami": [f"{Mohinur} ning telefon raqami: +998 91 496 11 08"],
    f"nozima ni raqami": [f"{Nozima} ning telefon raqami: +998 97 161 33 36"],
    f"farzona ni raqami": [f"{Farzona} ning telefon raqami: +998 94 611 66 76"],
    f"a odina ni raqami": [f"{Odinaxon_A} ning telefon raqami: +998 94 785 39 33"],
    f"shoiraxon ni raqami": [f"{Shoiraxon} ning telefon raqami: +998 99 647 18 77"],
    f"diyora ni raqami": [f"{Diyora} ning telefon raqami: +998 91 486 42 40"],
    f"madinabonu ni raqami": [f"{Madinabonu} ning telefon raqami: +998 88 064 17 47"],
    f"omadxon ni raqami": [f"{Omadxon} ning telefon raqami: +998 88 999 70 02"],
    f"bibihojar ni raqami": [f"{Bibihojar} ning telefon raqami: +998 94 012 52 17"],
    f"gulizebo ni raqami": [f"{Gulizebo} ning telefon raqami: +998 94 263 13 05"],
    f"robiya ni raqami": [f"{Robiya} ning telefon raqami: +998 93 667 11 81"],
    f"donoxon ni raqami": [f"{Donoxon} ning telefon raqami: +998 91 605 48 16"],
    f"odina sh ni raqami": [f"{Odinaxon_Sh} ning telefon raqami: +998 94 784 40 06"],
    f"oltinoy ni raqami": [f"{Oltinoy} ning telefon raqami: +998 88 582 18 05"],
    f"jasurbek ni raqami": [f"{Jasurbek} ning telefon raqami: +998 88 204 11 02"],
    f"aliakbar ni raqami": [f"{Aliakbar} ning raqami: +998 93 541 71 57"],
    f"abduraxmonbek ni raqami": [f"{Abduraxmonbek} ning telefon raqami: +998914907110"],
    f"intizor ni raqami": [f"{Intizor} ning telefon raqami: +998 94 398 22 26"],
    f"rahmon ninraqami": [f"{Rahmon} ning telefon raqami: +998 77 777 53 03"],
    f"abduraxim ni raqami": [f"{Abduraxim} ning telefon raqami: +998 91 612 05 25"],
    f"bahodir y ni raqami": [f"{Bahodirjon_Y} ning telefon raqami: +998 90 832 39 94"],
    f"sharofat ni raqami": [f"{Sharofat} ning telefon raqami: +998 50 220 22 81"],
    f"bibiruqiya ni raqami": [f"{Bibiruqiya} ning telefon raqami: +998 88 959 08 28"], 
    f"baxodir m ni raqami": [f"{Baxodir_M} ning telefon raqami: +998 93 248 58 10"],
        
    f"{zahro}ning pasport raqami": [f"{Zahro} ning pasport raqami: AD2665023"],
    f"{malika}ning pasport raqami": [f"{Malika} ning pasport raqami: AD0916530"],
    f"{mohinur}ning pasport raqami": [f"{Mohinur} ning pasport raqami: AD0591626"],
    f"{nozima}ning pasport raqami": [f"{Nozima} ning pasport raqami: AD0855888"],
    f"{farzona}ning pasport raqami": [f"{Farzona} ning pasport raqami: AD1660083"],
    f"{odinaxon_a}ning pasport raqami": [f"{Odinaxon_A} ning pasport raqami: AD0714184"],
    f"{shoiraxon}ning pasport raqami": [f"{Shoiraxon} ning pasport raqami: AD1856033"],
    f"{diyora}ning pasport raqami": [f"{Diyora} ning pasport raqami: AD1333664"],
    f"{madinabonu}ning pasport raqami": [f"{Madinabonu} ning pasport raqami: AD0983013"],
    f"{omadxon}ning pasport raqami": [f"{Omadxon} ning pasport raqami: AD0240224"],
    f"{bibihojar}ning pasport raqami": [f"{Bibihojar} ning pasport raqami: AD0876991"],
    f"{gulizebo}ning pasport raqami": [f"{Gulizebo} ning pasport raqami: AD1172727"],
    f"{robiya}ning pasport raqami": [f"{Robiya} ning pasport raqami: AD1287391"],
    f"{donoxon}ning pasport raqami": [f"{Donoxon} ning pasport raqami: AD1006466"],
    f"{odinaxon_sh}ning pasport raqami": [f"{Odinaxon_Sh} ning pasport raqami: AD2091487"],
    f"{oltinoy}ning pasport raqami": [f"{Oltinoy} ning pasport raqami: Bu haqida hozircha ma'lumot yo'q! Guruhga keyinchalik qo'shilgan bo'lishi mumkin."],
    f"{jasurbek}ning pasport raqami": [f"{Jasurbek} ning pasport raqami: AD1701587"],
    f"{aliakbar}ning pasport raqami": [f"{Aliakbar} ning pasport raqami: AC1652439"],
    f"{abduraxmonbek}ning pasport raqami": [f"{Abduraxmonbek} ning pasport raqami: AD0748728"],
    f"{intizor}ning pasport raqami": [f"{Intizor} ning pasport raqami: AD0936187"],
    f"{rahmon}ning pasport raqami": [f"{Rahmon} ning pasport raqami: AC1581878"],
    f"{abduraxim}ning pasport raqami": [f"{Abduraxim} ning pasport raqami: AD1276934"],
    f"{bahodirjon_y}ning pasport raqami": [f"{Bahodirjon_Y} ning pasport raqami: AD0105962"],
    f"{sharofat}ning pasport raqami": [f"{Sharofat} ning pasport raqami: AD2013868"],
    f"{bibiruqiya}ning pasport raqami": [f"{Bibiruqiya} ning pasport raqami: AD1345975"],
    f"{baxodir_m}ning pasport raqami": [f"{Baxodir_M} ning pasport raqami: AD1113952"],
    f"bahodir y ning pasport raqami": [f"{Bahodirjon_Y} ning pasport raqami: AD0105962"],
    f"bahodir m ning pasport raqami": [f"{Baxodir_M} ning pasport raqami: AD1113952"],
    f"odina a ning pasport raqami": [f"{Odinaxon_A} ning pasport raqami: AD0714184"],
    f"odina sh ning pasport raqami": [f"{Odinaxon_Sh} ning pasport raqami: AD2091487"],
    f"{zahro} pasport raqami": [f"{Zahro} ning pasport raqami: AD2665023"],
    f"{malika} pasport raqami": [f"{Malika} ning pasport raqami: AD0916530"],
    f"{mohinur} pasport raqami": [f"{Mohinur} ning pasport raqami: AD0591626"],
    f"{nozima} pasport raqami": [f"{Nozima} ning pasport raqami: AD0855888"],
    f"{farzona} pasport raqami": [f"{Farzona} ning pasport raqami: AD1660083"],
    f"{odinaxon_a} pasport raqami": [f"{Odinaxon_A} ning pasport raqami: AD0714184"],
    f"{shoiraxon} pasport raqami": [f"{Shoiraxon} ning pasport raqami: AD1856033"],
    f"{diyora} pasport raqami": [f"{Diyora} ning pasport raqami: AD1333664"],
    f"{madinabonu} pasport raqami": [f"{Madinabonu} ning pasport raqami: AD0983013"],
    f"{omadxon} pasport raqami": [f"{Omadxon} ning pasport raqami: AD0240224"],
    f"{bibihojar} pasport raqami": [f"{Bibihojar} ning pasport raqami: AD0876991"],
    f"{gulizebo} pasport raqami": [f"{Gulizebo} ning pasport raqami: AD1172727"],
    f"{robiya} pasport raqami": [f"{Robiya} ning pasport raqami: AD1287391"],
    f"{donoxon} pasport raqami": [f"{Donoxon} ning pasport raqami: AD1006466"],
    f"{odinaxon_sh} pasport raqami": [f"{Odinaxon_Sh} ning pasport raqami: AD2091487"],
    f"{oltinoy} pasport raqami": [f"{Oltinoy} ning pasport raqami: Bu haqida hozircha ma'lumot yo'q! Guruhga keyinchalik qo'shilgan bo'lishi mumkin."],
    f"{jasurbek} pasport raqami": [f"{Jasurbek} ning pasport raqami: AD1701587"],
    f"{aliakbar} pasport raqami": [f"{Aliakbar} ning pasport raqami: AC1652439"],
    f"{abduraxmonbek} pasport raqami": [f"{Abduraxmonbek} ning pasport raqami: AD0748728"],
    f"{intizor} pasport raqami": [f"{Intizor} ning pasport raqami: AD0936187"],
    f"{rahmon} pasport raqami": [f"{Rahmon} ning pasport raqami: AC1581878"],
    f"{abduraxim} pasport raqami": [f"{Abduraxim} ning pasport raqami: AD1276934"],
    f"{bahodirjon_y} pasport raqami": [f"{Bahodirjon_Y} ning pasport raqami: AD0105962"],
    f"{sharofat} pasport raqami": [f"{Sharofat} ning pasport raqami: AD2013868"],
    f"{bibiruqiya} pasport raqami": [f"{Bibiruqiya} ning pasport raqami: AD1345975"],
    f"{baxodir_m} pasport raqami": [f"{Baxodir_M} ning pasport raqami: AD1113952"],
    f"bahodir y pasport raqami": [f"{Bahodirjon_Y} ning pasport raqami: AD0105962"],
    f"bahodir m pasport raqami": [f"{Baxodir_M} ning pasport raqami: AD1113952"],
    f"odina a pasport raqami": [f"{Odinaxon_A} ning pasport raqami: AD0714184"],
    f"odina sh pasport raqami": [f"{Odinaxon_Sh} ning pasport raqami: AD2091487"],
    f"{zahro} pasport seriya raq": [f"{Zahro} ning pasport raqami: AD2665023"],
    f"{malika} pasport seriya raq": [f"{Malika} ning pasport raqami: AD0916530"],
    f"{mohinur} pasport seriya raq": [f"{Mohinur} ning pasport raqami: AD0591626"],
    f"{nozima} pasport seriya raq": [f"{Nozima} ning pasport raqami: AD0855888"],
    f"{farzona} pasport seriya raq": [f"{Farzona} ning pasport raqami: AD1660083"],
    f"{odinaxon_a} pasport seriya raq": [f"{Odinaxon_A} ning pasport raqami: AD0714184"],
    f"{shoiraxon} pasport seriya raq": [f"{Shoiraxon} ning pasport raqami: AD1856033"],
    f"{diyora} pasport seriya raq": [f"{Diyora} ning pasport raqami: AD1333664"],
    f"{madinabonu} pasport seriya raq": [f"{Madinabonu} ning pasport raqami: AD0983013"],
    f"{omadxon} pasport seriya raq": [f"{Omadxon} ning pasport raqami: AD0240224"],
    f"{bibihojar} pasport seriya raq": [f"{Bibihojar} ning pasport raqami: AD0876991"],
    f"{gulizebo} pasport seriya raq": [f"{Gulizebo} ning pasport raqami: AD1172727"],
    f"{robiya} pasport seriya raq": [f"{Robiya} ning pasport raqami: AD1287391"],
    f"{donoxon} pasport seriya raq": [f"{Donoxon} ning pasport raqami: AD1006466"],
    f"{odinaxon_sh} pasport seriya raq": [f"{Odinaxon_Sh} ning pasport raqami: AD2091487"],
    f"{oltinoy} pasport seriya raq": [f"{Oltinoy} ning pasport raqami: Bu haqida hozircha ma'lumot yo'q! Guruhga keyinchalik qo'shilgan bo'lishi mumkin."],
    f"{jasurbek} pasport seriya raq": [f"{Jasurbek} ning pasport raqami: AD1701587"],
    f"{aliakbar} pasport seriya raq": [f"{Aliakbar} ning pasport raqami: AC1652439"],
    f"{abduraxmonbek} pasport seriya raq": [f"{Abduraxmonbek} ning pasport raqami: AD0748728"],
    f"{intizor} pasport seriya raq": [f"{Intizor} ning pasport raqami: AD0936187"],
    f"{rahmon} pasport seriya raq": [f"{Rahmon} ning pasport raqami: AC1581878"],
    f"{abduraxim} pasport seriya raq": [f"{Abduraxim} ning pasport raqami: AD1276934"],
    f"{bahodirjon_y} pasport seriya raq": [f"{Bahodirjon_Y} ning pasport raqami: AD0105962"],
    f"{sharofat} pasport seriya raq": [f"{Sharofat} ning pasport raqami: AD2013868"],
    f"{bibiruqiya} pasport seriya raq": [f"{Bibiruqiya} ning pasport raqami: AD1345975"],
    f"{baxodir_m} pasport seriya raq": [f"{Baxodir_M} ning pasport raqami: AD1113952"],
    f"bahodir y pasport seriya raq": [f"{Bahodirjon_Y} ning pasport raqami: AD0105962"],
    f"bahodir m pasport seriya raq": [f"{Baxodir_M} ning pasport raqami: AD1113952"],
    f"odina a pasport seriya raq": [f"{Odinaxon_A} ning pasport raqami: AD0714184"],
    f"odina sh pasport seriya raq": [f"{Odinaxon_Sh} ning pasport raqami: AD2091487"],
    
    "pasport raqami seriyasi": ["Aynan kimni pasport seriya raqami kerak. Misol uchun (Alini pasport raqami)"],
    "pasport raqami": ["Aynan kimni pasport seriya raqami kerak. Misol uchun (Alini pasport raqami)"],
    "pasport seriyasi": ["Aynan kimni pasport seriya raqami kerak. Misol uchun (Alini pasport raqami)"],
    "jshshir" : ["Aynan kimning JSHSHIR raqami kerak? to'liqroq malumot bering. (Masalan: Vali jshshir)"],
    "jshshr" : ["Aynan kimning JSHSHIR raqami kerak? to'liqroq malumot bering. (Masalan: Vali jshshir)"],
    "jshr" : ["Aynan kimning JSHSHIR raqami kerak? to'liqroq malumot bering. (Masalan: Vali jshshir)"],
    "telefon raqami kerak!": ["Kimning raqami kerak?"],
    "biror narsa": ["Boshqa gap topolmadizmi?"],
    "ha": ["Ha shunaqa deng. Sizga yana qanday yordam kerak?"],
    
    f"{zahro} jshshir": [f"{Zahro} JSHSHIR raqami: 62104065140014"],
    f"{malika} jshshir": [f"{Malika} JSHSHIR raqami: 62910055150031"],
    f"{mohinur} jshshir": [f"{Mohinur} JSHSHIR raqami: 61408055180017"],
    f"{nozima} jshshir": [f"{Nozima} JSHSHIR raqami: 63103055040061"],
    f"{farzona} jshshir": [f"{Farzona} JSHSHIR raqami: 63008057020081"],
    f"{shoiraxon} jshshir": [f"{Shoiraxon} JSHSHIR raqami: 62111055190041"],
    f"{diyora} jshshir": [f"{Diyora} JSHSHIR raqami: 62206055170015"],
    f"{madinabonu} jshshir": [f"{Madinabonu} JSHSHIR raqami: none"],
    f"{omadxon} jshshir": [f"{Omadxon} JSHSHIR raqami: 60503055130053"],
    f"{bibihojar} jshshir": [f"{Bibihojar} JSHSHIR raqami: 60810055190018"],
    f"{gulizebo} jshshir": [f"{Gulizebo} JSHSHIR raqami: 61303065140034"],
    f"{robiya} jshshir": [f"{Robiya} JSHSHIR raqami: none"],
    f"{donoxon} jshshir": [f"{Donoxon} JSHSHIR raqami: 61108055200057"],
    f"{oltinoy} jshshir": [f"{Oltinoy} JSHSHIR raqami: none"],
    f"{jasurbek} jshshir": [f"{Jasurbek} JSHSHIR raqami: 52111057070014"],
    f"{aliakbar} jshshir": [f"{Aliakbar} JSHSHIR raqami: 53008025200085"],
    f"{abduraxmonbek} jshshir": [f"{Abduraxmonbek} JSHSHIR raqami: 50507055040054"],
    f"{intizor} jshshir": [f"{Intizor} JSHSHIR raqami: 61111055200015"],
    f"{rahmon} jshshir": [f"{Rahmon} JSHSHIR raqami: 50401035420013"],
    f"{abduraxim} jshshir": [f"{Abduraxim} JSHSHIR raqami: 51601055180042"],
    f"{sharofat} jshshir": [f"{Sharofat} JSHSHIR raqami: 60309065890024"],
    f"{bibiruqiya} jshshir": [f"{Bibiruqiya} JSHSHIR raqami: 62407057020034"],
    f"{odinaxon_a} jshshir": [f"{Odinaxon_A} JSHSHIR raqami: 61401055180078"],
    f"{odinaxon_sh} jshshir": [f"{Odinaxon_Sh} JSHSHIR raqami: 62001066930070"],
    f"{bahodirjon_y} jshshir": [f"{Bahodirjon_Y} JSHSHIR raqami: 52901046960024"],
    f"{baxodir_m} jshshir": [f"{Baxodir_M} JSHSHIR raqami: 52410055180100"],
    f"odina a jshshir": [f"{Odinaxon_A} JSHSHIR raqami: 61401055180078"],
    f"odina sh jshshir": [f"{Odinaxon_Sh} JSHSHIR raqami: 62001066930070"],
    f"bahodir y jshshir": [f"{Bahodirjon_Y} JSHSHIR raqami: 52901046960024"],
    f"baxodir m jshshir": [f"{Baxodir_M} JSHSHIR raqami: 52410055180100"],
    f"{zahro} jshr": [f"{Zahro} JSHSHIR raqami: 62104065140014"],
    f"{malika} jshr": [f"{Malika} JSHSHIR raqami: 62910055150031"],
    f"{mohinur} jshr": [f"{Mohinur} JSHSHIR raqami: 61408055180017"],
    f"{nozima} jshr": [f"{Nozima} JSHSHIR raqami: 63103055040061"],
    f"{farzona} jshr": [f"{Farzona} JSHSHIR raqami: 63008057020081"],
    f"{shoiraxon} jshshir": [f"{Shoiraxon} JSHSHIR raqami: 62111055190041"],
    f"{diyora} jshr": [f"{Diyora} JSHSHIR raqami: 62206055170015"],
    f"{madinabonu} jshr": [f"{Madinabonu} JSHSHIR raqami: 60903055200033"],
    f"{omadxon} jshr": [f"{Omadxon} JSHSHIR raqami: 60503055130053"],
    f"{bibihojar} jshr": [f"{Bibihojar} JSHSHIR raqami: 60810055190018"],
    f"{gulizebo} jshr": [f"{Gulizebo} JSHSHIR raqami: 61303065140034"],
    f"{robiya} jshr": [f"{Robiya} JSHSHIR raqami: 62403065040044"],
    f"{donoxon} jshr": [f"{Donoxon} JSHSHIR raqami: 61108055200057"],
    f"{oltinoy} jshr": [f"{Oltinoy} JSHSHIR raqami: Bu qiz haqida to'liq ma'lumotlar mavjud emas!"],
    f"{jasurbek} jshr": [f"{Jasurbek} JSHSHIR raqami: 52111057070014"],
    f"{aliakbar} jshr": [f"{Aliakbar} JSHSHIR raqami: 53008025200085"],
    f"{abduraxmonbek} jshr": [f"{Abduraxmonbek} JSHSHIR raqami: 50507055040054"],
    f"{intizor} jshr": [f"{Intizor} JSHSHIR raqami: 61111055200015"],
    f"{rahmon} jshr": [f"{Rahmon} JSHSHIR raqami: 50401035420013"],
    f"{abduraxim} jshr": [f"{Abduraxim} JSHSHIR raqami: 51601055180042"],
    f"{sharofat} jshr": [f"{Sharofat} JSHSHIR raqami: 60309065890024"],
    f"{bibiruqiya} jshr": [f"{Bibiruqiya} JSHSHIR raqami: 62407057020034"],
    f"{odinaxon_a} jshr": [f"{Odinaxon_A} JSHSHIR raqami: 61401055180078"],
    f"{odinaxon_sh} jshr": [f"{Odinaxon_Sh} JSHSHIR raqami: 62001066930070"],
    f"{bahodirjon_y} jshr": [f"{Bahodirjon_Y} JSHSHIR raqami: 52901046960024"],
    f"{baxodir_m} jshr": [f"{Baxodir_M} JSHSHIR raqami: 52410055180100"],
    f"odina a jshr": [f"{Odinaxon_A} JSHSHIR raqami: 61401055180078"],
    f"odina sh jshr": [f"{Odinaxon_Sh} JSHSHIR raqami: 62001066930070"],
    f"bahodir y jshr": [f"{Bahodirjon_Y} JSHSHIR raqami: 52901046960024"],
    f"baxodir m jshr": [f"{Baxodir_M} JSHSHIR raqami: 52410055180100"],
    f"baxodir jshshir": [f"Guruhda 2 ta Baxodir mavjud! To'liqroq yozing. (Misol: Bahodir Y jshshir)"],
    f"baxodir jshr": [f"Guruhda 2 ta Baxodir mavjud! To'liqroq yozing. (Misol: Bahodir Y jshshir)"],
    f"odina jshshir": [f"Guruhda 2 ta Odina mavjud! To'liqroq yozing. (Misol: Odina SH jshshir)"],
    f"odina jshr": [f"Guruhda 2 ta Odina mavjud! To'liqroq yozing. (Misol: Odina SH jshshir)"],
    
    f"{zahro} yashash manzil": [f"{Zahro} manzili: Andijon viloyati, Izboskan tumani"],
    f"{malika} yashash manzil": [f"{Malika} manzili: Andijon viloyati, Qo‘rg‘ontepa tumani"],
    f"{mohinur} yashash manzil": [f"{Mohinur} manzili: Andijon viloyati, Shaxrixon tumani"],
    f"{nozima} yashash manzil": [f"{Nozima} manzili: Andijon viloyati, Andijon tumani"],
    f"{farzona} yashash manzil": [f"{Farzona} manzili: Farg‘ona viloyati, Dang‘ara tumani"],
    f"{shoiraxon} yashash manzil": [f"{Shoiraxon} manzili: Andijon viloyati, Paxtaobod tumani"],
    f"{diyora} yashash manzil": [f"{Diyora} manzili: Andijon viloyati, Marxamat tumani"],
    f"{madinabonu} yashash manzil": [f"{Madinabonu} manzili: Andijon viloyati, Asaka tumani"],
    f"{omadxon} yashash manzil": [f"{Omadxon} manzili: Andijon viloyati, Jalaquduq tumani"],
    f"{bibihojar} yashash manzil": [f"{Bibihojar} manzili: Andijon viloyati, Paxtaobod tumani"],
    f"{gulizebo} yashash manzil": [f"{Gulizebo} manzili: Andijon viloyati, Izboskan tumani"],
    f"{robiya} yashash manzil": [f"{Robiya} manzili: Andijon shahar"],
    f"{donoxon} yashash manzil": [f"{Donoxon} manzili: Andijon viloyati, Asaka tumani"],
    f"{oltinoy} yashash manzil": [f"{Oltinoy} manzili: Yaxshi joyda yashaydi. Aniq ma'lumot yo'q hozircha."],
    f"{jasurbek} yashash manzil": [f"{Jasurbek} manzili: Farg‘ona viloyati, Quvasoy shahri"],
    f"{aliakbar} manzil": [f"{Aliakbar} manzili: Andijon viloyati, Asaka tumani"],
    f"{abduraxmonbek} yashash manzili": [f"{Abduraxmonbek} manzili: Andijon viloyati, Andijon tumani"],
    f"{intizor} yashash manzil": [f"{Intizor} manzili: Andijon viloyati, Asaka tumani"],
    f"{rahmon} yashash anzil": [f"{Rahmon} manzili: Jizzax viloyati, Arnasoy tumani"],
    f"{abduraxim} yashash manzil": [f"{Abduraxim} manzili: Andijon viloyati, Shaxrixon tumani"],
    f"{sharofat} yashash manzil": [f"{Sharofat} manzili: Namangan viloyati, Chortoq tumani"],
    f"{bibiruqiya} yashash manzil": [f"{Bibiruqiya} manzili: Farg‘ona viloyati, Dang‘ara tumani"],
    f"{odinaxon_a} yashash manzil": [f"{Odinaxon_A} manzili: Andijon viloyati, Shaxrixon tumani"],
    f"{odinaxon_sh} yashash manzil": [f"{Odinaxon_Sh} manzili: Farg‘ona viloyati, Beshariq tumani"],
    f"{bahodirjon_y} yashash manzil": [f"{Bahodirjon_Y} manzili: Farg‘ona viloyati, Rishton tumani"],
    f"{baxodir_m} yashash manzil": [f"{Baxodir_M} manzili: Andijon viloyati, Shaxrixon tumani"],
    
    f"{zahro} manzil": [f"{Zahro} manzili: Andijon viloyati, Izboskan tumani"],
    f"{malika} manzil": [f"{Malika} manzili: Andijon viloyati, Qo‘rg‘ontepa tumani"],
    f"{mohinur} manzil": [f"{Mohinur} manzili: Andijon viloyati, Shaxrixon tumani"],
    f"{nozima} manzil": [f"{Nozima} manzili: Andijon viloyati, Andijon tumani"],
    f"{farzona} manzil": [f"{Farzona} manzili: Farg‘ona viloyati, Dang‘ara tumani"],
    f"{shoiraxon} manzil": [f"{Shoiraxon} manzili: Andijon viloyati, Paxtaobod tumani"],
    f"{diyora} manzil": [f"{Diyora} manzili: Andijon viloyati, Marxamat tumani"],
    f"{madinabonu} manzil": [f"{Madinabonu} manzili: Andijon viloyati, Asaka tumani"],
    f"{omadxon} manzil": [f"{Omadxon} manzili: Andijon viloyati, Jalaquduq tumani"],
    f"{bibihojar} manzil": [f"{Bibihojar} manzili: Andijon viloyati, Paxtaobod tumani"],
    f"{gulizebo} manzil": [f"{Gulizebo} manzili: Andijon viloyati, Izboskan tumani"],
    f"{robiya} manzil": [f"{Robiya} manzili: Andijon shahar"],
    f"{donoxon} manzil": [f"{Donoxon} manzili: Andijon viloyati, Asaka tumani"],
    f"{oltinoy} manzil": [f"{Oltinoy} manzili: Yaxshi joyda yashaydi. Aniq ma'lumot yo'q hozircha."],
    f"{jasurbek} manzil": [f"{Jasurbek} manzili: Farg‘ona viloyati, Quvasoy shahri"],
    f"{aliakbar} manzil": [f"{Aliakbar} manzili: Andijon viloyati, Asaka tumani"],
    f"{abduraxmonbek} manzili": [f"{Abduraxmonbek} manzili: Andijon viloyati, Andijon tumani"],
    f"{intizor} manzil": [f"{Intizor} manzili: Andijon viloyati, Asaka tumani"],
    f"{rahmon} anzil": [f"{Rahmon} manzili: Jizzax viloyati, Arnasoy tumani"],
    f"{abduraxim} manzil": [f"{Abduraxim} manzili: Andijon viloyati, Shaxrixon tumani"],
    f"{sharofat} manzil": [f"{Sharofat} manzili: Namangan viloyati, Chortoq tumani"],
    f"{bibiruqiya} manzil": [f"{Bibiruqiya} manzili: Farg‘ona viloyati, Dang‘ara tumani"],
    f"{odinaxon_a} manzil": [f"{Odinaxon_A} manzili: Andijon viloyati, Shaxrixon tumani"],
    f"{odinaxon_sh} manzil": [f"{Odinaxon_Sh} manzili: Farg‘ona viloyati, Beshariq tumani"],
    f"{bahodirjon_y} manzil": [f"{Bahodirjon_Y} manzili: Farg‘ona viloyati, Rishton tumani"],
    f"{baxodir_m} manzil": [f"{Baxodir_M} manzili: Andijon viloyati, Shaxrixon tumani"],
    f"odina a manzil": [f"{Odinaxon_A} manzili: Andijon viloyati, Shaxrixon tumani"],
    f"odina sh manzil": [f"{Odinaxon_Sh} manzili: Farg‘ona viloyati, Beshariq tumani"],
    f"bahodir y manzil": [f"{Bahodirjon_Y} manzili: Farg‘ona viloyati, Rishton tumani"],
    f"baxodir m manzil": [f"{Baxodir_M} manzili: Andijon viloyati, Shaxrixon tumani"],
    f"baxodir manzil": [f"Guruhda 2 ta Baxodir mavjud! To'liqroq yozing. (Misol: Bahodir Y manzili)"],
    f"odina manzil": [f"Guruhda 2 ta Odina mavjud! To'liqroq yozing. (Misol: Odina SH manzili)"],
    
    f"{bibihojar} sanasi": [f"{Bibihojar} tug'ilgan sana: 2005-10-08"],
    f"{abduraxim} sanasi": [f"{Abduraxim} tug'ilgan sana: 2005-01-16"],
    f"{zahro} sanasi": [f"{Zahro} tug'ilgan sana: 2006-04-21"],
    f"{odinaxon_sh} sanasi": [f"{Odinaxon_Sh} tug'ilgan sana: 2006-01-20"],
    f"{bibiruqiya} sanasi": [f"{Bibiruqiya} tug'ilgan sana: 2005-07-24"],
    f"{aliakbar} sanasi": [f"{Aliakbar} tug'ilgan sana: 2002-08-30"],
    f"{rahmon} sanasi": [f"{Rahmon} tug'ilgan sana: 2003-01-04"],
    f"{baxodir_m} sanasi": [f"{Baxodir_M} tug'ilgan sana: 2005-10-24"],
    f"{mohinur} sanasi": [f"{Mohinur} tug'ilgan sana: 2005-08-14"],
    f"{odinaxon_a} sanasi": [f"{Odinaxon_A} tug'ilgan sana: 2005-01-14"],
    f"{donoxon} sanasi": [f"{Donoxon} tug'ilgan sana: 2005-08-11"],
    f"{bahodirjon_y} sanasi": [f"{Bahodirjon_Y} tug'ilgan sana: 2004-01-29"],
    f"{malika} sanasi": [f"{Malika} tug'ilgan sana: 2005-10-29"],
    f"{madinabonu} sanasi": [f"{Madinabonu} tug'ilgan sana: 2005-03-09"],
    f"{gulizebo} sanasi": [f"{Gulizebo} tug'ilgan sana: 2006-03-13"],
    f"{sharofat} sanasi": [f"{Sharofat} tug'ilgan sana: 2006-09-03"],
    f"{shoiraxon} sanasi": [f"{Shoiraxon} tug'ilgan sana: 2005-11-21"],
    f"{farzona} sanasi": [f"{Farzona} tug'ilgan sana: 2005-08-30"],
    f"{omadxon} sanasi": [f"{Omadxon} tug'ilgan sana: 2005-03-05"],
    f"{abduraxmonbek} sanasi": [f"{Abduraxmonbek} tug'ilgan sana: 2005-07-05"],
    f"{jasurbek} sanasi": [f"{Jasurbek} tug'ilgan sana: 2005-11-21"],
    f"{diyora} sanasi": [f"{Diyora} tug'ilgan sana: 2005-06-22"],
    f"{intizor} sanasi": [f"{Intizor} tug'ilgan sana: 2005-11-11"],
    f"{nozima} sanasi": [f"{Nozima} tug'ilgan sana: 2005-03-31"],
    f"{robiya} sanasi": [f"{Robiya} tug'ilgan sana: 2006-03-24"],
    f"{nozima} sanasi": [f"{Nozima} tug'ilgan sana: 2005-03-31"],
    f"odina a sanasi": [f"{Odinaxon_A} tug'ilgan sana: 2005-01-14"],
    f"odina sh sanasi": [f"{Odinaxon_Sh} tug'ilgan sana: 2006-01-20"],
    f"bahodir y sanasi": [f"{Bahodirjon_Y} tug'ilgan sana: 2004-01-29"],
    f"baxodir m sanasi": [f"{Baxodir_M} tug'ilgan sana: 2005-10-24"],
    f"baxodir sanasi": [f"Guruhda 2 ta Baxodir mavjud! To'liqroq yozing. (Misol: Bahodir Y tug'ilgan sananasi)"],
    f"odina sanasi": [f"Guruhda 2 ta Odina mavjud! To'liqroq yozing. (Misol: Odina SH tig'ilgan sanasi)"],

    f"{bibihojar} hemis id": [f"{Bibihojar}hemis id: 2005-10-08"],
    f"{abduraxim} tug'ilgan sanasi": [f"{Abduraxim} tug'ilgan sana: 2005-01-16"],
    f"{zahro} tug'ilgan sanasi": [f"{Zahro} tug'ilgan sana: 2006-04-21"],
    f"{odinaxon_sh} tug'ilgan sanasi": [f"{Odinaxon_Sh} tug'ilgan sana: 2006-01-20"],
    f"{bibiruqiya} tug'ilgan sanasi": [f"{Bibiruqiya} tug'ilgan sana: 2005-07-24"],
    f"{aliakbar} tug'ilgan sanasi": [f"{Aliakbar} tug'ilgan sana: 2002-08-30"],
    f"{rahmon} tug'ilgan sanasi": [f"{Rahmon} tug'ilgan sana: 2003-01-04"],
    f"{baxodir_m} sanasi": [f"{Baxodir_M} tug'ilgan sana: 2005-10-24"],
    f"{mohinur} tug'ilgan sanasi": [f"{Mohinur} tug'ilgan sana: 2005-08-14"],
    f"{odinaxon_a} tug'ilgan sanasi": [f"{Odinaxon_A} tug'ilgan sana: 2005-01-14"],
    f"{donoxon} tug'ilgan sanasi": [f"{Donoxon} tug'ilgan sana: 2005-08-11"],
    f"{bahodirjon_y} tug'ilgan sanasi": [f"{Bahodirjon_Y} tug'ilgan sana: 2004-01-29"],
    f"{malika} tug'ilgan sanasi": [f"{Malika} tug'ilgan sana: 2005-10-29"],
    f"{madinabonu} tug'ilgan sanasi": [f"{Madinabonu} tug'ilgan sana: 2005-03-09"],
    f"{gulizebo} tug'ilgan sanasi": [f"{Gulizebo} tug'ilgan sana: 2006-03-13"],
    f"{sharofat} tug'ilgan sanasi": [f"{Sharofat} tug'ilgan sana: 2006-09-03"],
    f"{shoiraxon} tug'ilgan sanasi": [f"{Shoiraxon} tug'ilgan sana: 2005-11-21"],
    f"{farzona} tug'ilgan sanasi": [f"{Farzona} tug'ilgan sana: 2005-08-30"],
    f"{omadxon} tug'ilgan sanasi": [f"{Omadxon} tug'ilgan sana: 2005-03-05"],
    f"{abduraxmonbek} tug'ilgan sanasi": [f"{Abduraxmonbek} tug'ilgan sana: 2005-07-05"],
    f"{jasurbek} tug'ilgan sanasi": [f"{Jasurbek} tug'ilgan sana: 2005-11-21"],
    f"{diyora} tug'ilgan sanasi": [f"{Diyora} tug'ilgan sana: 2005-06-22"],
    f"{intizor} tug'ilgan sanasi": [f"{Intizor} tug'ilgan sana: 2005-11-11"],
    f"{nozima} tug'ilgan sanasi": [f"{Nozima} tug'ilgan sana: 2005-03-31"],
    f"{robiya} tug'ilgan sanasi": [f"{Robiya} tug'ilgan sana: 2006-03-24"],
    f"{nozima} tug'ilgan sanasi": [f"{Nozima} tug'ilgan sana: 2005-03-31"],
    f"odina a tug'ilgan sanasi": [f"{Odinaxon_A} tug'ilgan sana: 2005-01-14"],
    f"odina sh tug'ilgan sanasi": [f"{Odinaxon_Sh} tug'ilgan sana: 2006-01-20"],
    f"bahodir y tug'ilgan sanasi": [f"{Bahodirjon_Y} tug'ilgan sana: 2004-01-29"],
    f"baxodir m tug'ilgan sanasi": [f"{Baxodir_M} tug'ilgan sana: 2005-10-24"],
    f"baxodir tug'ilgan sanasi": [f"Guruhda 2 ta Baxodir mavjud! To'liqroq yozing. (Misol: Bahodir Y tug'ilgan sananasi)"],
    f"odina tug'ilgan sanasi": [f"Guruhda 2 ta Odina mavjud! To'liqroq yozing. (Misol: Odina SH tig'ilgan sanasi)"],
    
    f"{bibihojar} hemis id": [f"{bibihojar} hemis id: 301231100103"],
    f"{abduraxim} hemis id": [f"{abduraxim} hemis id: 301231100115"],
    f"{zahro} hemis id": [f"{Zahro} hemis id: 301231101135"],
    f"{odinaxon_a} hemis id": [f"{Odinaxon_A} hemis id: 301231100986"],
    f"{bibiruqiya} hemis id": [f"{Bibiruqiya} hemis id: 301231100983"],
    f"{aliakbar} hemis id": [f"{Aliakbar} hemis id: 301231100990"],
    f"{rahmon} hemis id": [f"{rahmon} hemis id: 301231101102"],
    f"{baxodir_m} hemis id": [f"{Baxodir_M} hemis id: 301231101105"],
    f"{mohinur} hemis id": [f"{Mohinur} hemis id: 301231101110"],
    f"{odinaxon_sh} hemis id": [f"{Odinaxon_Sh} hemis id: 301231101113"],
    f"{donoxon} hemis id": [f"{donoxon} hemis id: 301231101114"],
    f"{bahodirjon_y} hemis id": [f"{Bahodirjon_Y} hemis id: 301231101115"],
    f"{malika} hemis id": [f"{Malika} hemis id: 301231101116"],
    f"{madinabonu} hemis id": [f"{Madinabonu} hemis id: 301231101335"],
    f"{gulizebo} hemis id": [f"{Gulizebo} hemis id: 301231101384"],
    f"{sharofat} hemis id": [f"{Sharofat} hemis id: 301231101385"],
    f"{shoiraxon} hemis id": [f"{Shoiraxon} hemis id: 301231101386"],
    f"{farzona} hemis id": [f"{Farzona} hemis id: 301231101387"],
    f"{omadxon} hemis id": [f"{Omadxon} hemis id: 301231101388"],
    f"{abduraxmonbek} hemis id": [f"{Abduraxmonbek} hemis id: 301231101389"],
    f"{jasurbek} hemis id": [f"{Jasurbek} hemis id: 301231101392"],
    f"{diyora} hemis id": [f"{Diyora} hemis id: 301231101394"],
    f"{intizor} hemis id": [f"{Intizor} hemis id: 301231101395"],
    f"{nozima} hemis id": [f"{Nozima} hemis id: 301231101393"]

}